---

AWSTemplateFormatVersion: "2010-09-09"
Description: >
    state-machine

Transform: AWS::Serverless-2016-10-31

Resources:
    Machine:
        Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
        Properties:
            DefinitionUri: state-model/stepper.json
            DefinitionSubstitutions:
                OneFunctionArn: !GetAtt One.Arn
                TwoFunctionArn: !GetAtt Two.Arn
                ThreeFunctionArn: !GetAtt Three.Arn
            Events:
                HourlyTradingSchedule:
                    Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
                    Properties:
                        Description: Schedule
                        Enabled: True
                        Schedule: "rate(5 minute)"
            Policies: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
                -   LambdaInvokePolicy:
                        FunctionName: !Ref One
                -   LambdaInvokePolicy:
                        FunctionName: !Ref Two
                -   LambdaInvokePolicy:
                        FunctionName: !Ref Three

    One:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: functions/step-function-1
            Handler: index.handler
            Runtime: nodejs14.x

    Two:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: functions/step-function-2
            Handler: index.handler
            Runtime: nodejs14.x

    Three:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: functions/step-function-3
            Handler: index.handler
            Runtime: nodejs14.x

Outputs:
    ARN:
        Description: "State Machine ARN"
        Value: !Ref Machine
    IAM:
        Description: "IAM Role for State Machine's SAM Policy Templates"
        Value: !GetAtt Machine.Arn